backend: &BACKEND backend.j2
kafka: &KAFKA kafka.j2
kafdrop: &KAFDROP kafdrop.j2
webui: &WEBUI webui.j2
keydb: &KEYDB keydb.j2
mongo: &MONGO mongo.j2
minio: &MINIO minio.j2
msbridge: &MSBRIDGE ms-bridge.j2

source:
  template_dir: .templates
  outputs: compose.yml
  env_files:
    - apps/backend/env/.env
    - apps/backend/env/.env.local
    - apps/ms-bridge/env/.env
    - apps/ms-bridge/env/.env.local
    - .env.global

compose:
  - service.j2

  - template: *BACKEND
    environment:
      - TARGET: production
    depends_on:
      - *KEYDB
      - *MONGO
      - *MINIO

  - template: *KEYDB
  - template: *MONGO
  - template: *MINIO

  - template: *WEBUI
    depends_on:
      - *BACKEND

  - template: *MSBRIDGE
    depends_on:
      - *KEYDB

  - template: *KAFKA
    depends_on:
      - $USE_KAFKA
  - template: *KAFDROP
    depends_on:
      - *KAFKA
      - $USE_KAFKA

  - template: volumes.j2
  - template: networks.j2
