version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - acap
  - docpose
  - Hildt
  - kafdrop
  - keydb
  - MSBRIDGE
  - rabbitmq
  - truthyfy
  - WEBUI
ignoreWords: []
import: []
